### ISSUE TITLE
 which PX4  firmware should I use?

### ISSUE THREAD

**Issue by daydayupcg137** [castacks/PX4-fully-actuated#1]
![CM857%L%4$K6KKY4U49%FIO](https://user-images.githubusercontent.com/66363845/99795855-6f11de80-2b67-11eb-9436-1df01bb5a474.png)
Hello, I have made a six-rotor with a wheelbase of 550mm, which can adjust the tilt Angle around the arm. May I ask if your pX4 firmware can be used for control?Is "px4_fmu_v2_multicopter"?The other question is how many degrees can you achieve with a normal tilt Angle?

**Comment by keipour** [comment]
>     
> 
> ![CM857%L%4$K6KKY4U49%FIO](https://user-images.githubusercontent.com/66363845/99795855-6f11de80-2b67-11eb-9436-1df01bb5a474.png)
> 
> Hello, I have made a six-rotor with a wheelbase of 550mm, which can adjust the tilt Angle around the arm. May I ask if your pX4 firmware can be used for control?Is "px4_fmu_v2_multicopter"?The other question is how many degrees can you achieve with a normal tilt Angle?

Yes, you should be able to control your multirotor using this firmware. You can't use the pre-compiled binaries and should compile the firmware for your pixhawk/autopilot. I will post a detailed guide tomorrow.

**Comment by keipour** [comment]
> ![CM857%L%4$K6KKY4U49%FIO](https://user-images.githubusercontent.com/66363845/99795855-6f11de80-2b67-11eb-9436-1df01bb5a474.png)
> Hello, I have made a six-rotor with a wheelbase of 550mm, which can adjust the tilt Angle around the arm. May I ask if your pX4 firmware can be used for control?Is "px4_fmu_v2_multicopter"?The other question is how many degrees can you achieve with a normal tilt Angle?

The readme file is now updated with a guide on how to use the firmware. Please feel free to reach us if you have any questions.

**Comment by daydayupcg137** [comment]
Hello, I'm sorry that I confused the PX4 forum and your forum before, which led to a stupid question.
      I'm really sorry for that.Today I had a few problems during the compilation of your firmware, I clone your code in the ubuntu18.04 "git clone https://github.com/castacks/PX4-fully-actuated.git -- recursive", but I "make px4_fmu_v3_default" or use other compiler command, an error is as follows:







At 2020-11-22 05:38:05, "Azarakhsh Keipour" <notifications@github.com> wrote:


Hello, I have made a six-rotor with a wheelbase of 550mm, which can adjust the tilt Angle around the arm. May I ask if your pX4 firmware can be used for control?Is "px4_fmu_v2_multicopter"?The other question is how many degrees can you achieve with a normal tilt Angle?

The readme file is now updated with a guide on how to use the firmware. Please feel free to reach us if you have any questions.

**Comment by keipour** [comment]
I cannot see the error message. Would you please post the error message again?

**Comment by daydayupcg137** [comment]
Hello,when I "make px4_fmu-v3_default",the error is:


"FAILED: src/lib/version/build_git_version.h 

cd /home/cg/wort_src/PX4-fully-actuated && /usr/bin/python3 /home/cg/wort_src/PX4-fully-actuated/src/lib/version/px_update_git_header.py /home/cg/wort_src/PX4-fully-actuated/build/px4_fmu-v3_default/src/lib/version/build_git_version.h --validate




Error: the git tag 'f33b118dfb' does not match the expected format.




The expected format is 'v<PX4 version>[-<custom version>]'

  <PX4 version>: v<major>.<minor>.<patch>[-rc<rc>|-beta<beta>]

  <custom version>: <major>.<minor>.<patch>

Examples:

  v1.9.0rc3 (deprecated)

  v1.9.0-rc3 (preferred)

  v1.9.0-beta1

  v1.9.0-1.0.0

See also https://dev.px4.io/master/en/setup/building_px4.html#firmware_version




[14/1274] Performing configure step for 'px4io_firmware'

-- PX4 version: f33b118dfb

-- PX4 config file: /home/cg/wort_src/PX4-fully-actuated/boards/px4/io-v2/default.cmake

-- PX4 config: px4_io-v2_default

-- PX4 platform: nuttx

-- cmake build type: MinSizeRel

-- The CXX compiler identification is GNU 7.2.1

-- The C compiler identification is GNU 7.2.1

-- The ASM compiler identification is GNU

-- Found assembler: /home/cg/tools/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-gcc

-- Check for working CXX compiler: /home/cg/tools/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-g++

-- Check for working CXX compiler: /home/cg/tools/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-g++ -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

-- Check for working C compiler: /home/cg/tools/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-gcc

-- Check for working C compiler: /home/cg/tools/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-gcc -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Detecting C compile features

-- Detecting C compile features - done

-- ccache enabled (export CCACHE_DISABLE=1 to disable)

-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3") 

-- build type is MinSizeRel

-- PX4 ECL: Very lightweight Estimation & Control Library v1.9.0-rc1-182-g29cf788

-- Configuring done

-- Generating done

-- Build files have been written to: /home/cg/wort_src/PX4-fully-actuated/build/px4_fmu-v3_default/external/Build/px4io_firmware

ninja: build stopped: subcommand failed.

Makefile:193: recipe for target 'px4_fmu-v3_default' failed

make: *** [px4_fmu-v3_default] Error 1





Could you give me some advice?Thank you!













At 2020-11-23 23:42:58, "Azarakhsh Keipour" <notifications@github.com> wrote:

I cannot see the error message. Would you please post the error message again?

**Comment by daydayupcg137** [comment]
Hi, I am very interested in your recent paper"Attitude and Thrust Strategies for Fully Actuated Multirotors:The Fast-Track to Real-World Applications"。I have some questions I hope to get your answers
        how do you view The last two experiments and their data in your paper ?In The paper have such a words: "The figure illustrates The Angle staying almost constant while The multimotor performs aggressive motions", my question is tilt Angle is not what we fixed in advance?How to understand "The tilt Angle Staying almost Constant "?The final question is what does the data in Figure 10 illustrate compared to the data in Figure 9?




I sincerely hope to get your reply and answer. Thank you very much！







At 2020-11-23 23:42:58, "Azarakhsh Keipour" <notifications@github.com> wrote:

I cannot see the error message. Would you please post the error message again?

**Comment by keipour** [comment]
> Hello,when I "make px4_fmu-v3_default",the error is: "FAILED: src/lib/version/build_git_version.h cd /home/cg/wort_src/PX4-fully-actuated && /usr/bin/python3 /home/cg/wort_src/PX4-fully-actuated/src/lib/version/px_update_git_header.py /home/cg/wort_src/PX4-fully-actuated/build/px4_fmu-v3_default/src/lib/version/build_git_version.h --validate Error: the git tag 'f33b118dfb' does not match the expected format. The expected format is 'v<PX4 version>[-<custom version>]' <PX4 version>: v<major>.<minor>.<patch>[-rc<rc>|-beta<beta>] <custom version>: <major>.<minor>.<patch> Examples: v1.9.0rc3 (deprecated) v1.9.0-rc3 (preferred) v1.9.0-beta1 v1.9.0-1.0.0 See also https://dev.px4.io/master/en/setup/building_px4.html#firmware_version [14/1274] Performing configure step for 'px4io_firmware'
> […](#)
> -- PX4 version: [f33b118](https://github.com/castacks/PX4-fully-actuated/commit/f33b118dfb860a238c77d6a93a9f62b4f0881ad8)
> -- PX4 config file: /home/cg/wort_src/PX4-fully-actuated/boards/px4/io-v2/default.cmake
> -- PX4 config: px4_io-v2_default
> -- PX4 platform: nuttx
> -- cmake build type: MinSizeRel
> -- The CXX compiler identification is GNU 7.2.1
> -- The C compiler identification is GNU 7.2.1
> -- The ASM compiler identification is GNU
> -- Found assembler: /home/cg/tools/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-gcc
> -- Check for working CXX compiler: /home/cg/tools/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-g++
> -- Check for working CXX compiler: /home/cg/tools/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-g++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Check for working C compiler: /home/cg/tools/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-gcc
> -- Check for working C compiler: /home/cg/tools/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-gcc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- ccache enabled (export CCACHE_DISABLE=1 to disable)
> -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3")
> -- build type is MinSizeRel
> -- PX4 ECL: Very lightweight Estimation & Control Library v1.9.0-rc1-182-g29cf788
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/cg/wort_src/PX4-fully-actuated/build/px4_fmu-v3_default/external/Build/px4io_firmware ninja: build stopped: subcommand failed. Makefile:193: recipe for target 'px4_fmu-v3_default' failed make: *** [px4_fmu-v3_default] Error 1 Could you give me some advice?Thank you! At 2020-11-23 23:42:58, "Azarakhsh Keipour" <notifications@github.com> wrote: I cannot see the error message. Would you please post the error message again? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Sorry for the delay in responding. The issue was due to the tag not being uploaded to the repo. Please `git pull --tags` to update the tags on your computer and try building the code again. Just note that since you are compiling for fmu-v3, you probably need to comment some of the geometries in the CMakeFiles before your compilation to free some flash space. Please refer to README to see how you can do that.

**Comment by keipour** [comment]
> Hi, I am very interested in your recent paper"Attitude and Thrust Strategies for Fully Actuated Multirotors:The Fast-Track to Real-World Applications"。I have some questions I hope to get your answers how do you view The last two experiments and their data in your paper ?In The paper have such a words: "The figure illustrates The Angle staying almost constant while The multimotor performs aggressive motions", my question is tilt Angle is not what we fixed in advance?How to understand "The tilt Angle Staying almost Constant "?

You set the tilt angle in advance. In the specific case of Figure 10, the tilt angle and direction were estimated from the wind, but you can set it using the PX4 parameters instead (see README for more information about the parameters). The figure shows that while the UAV is flying around (not just hovering), the tilt angle can stay the same without much error.

Note that we are flying outdoors and our test site is pretty windy and has significant gusts, so keeping the angle error too low is hard. Nevertheless, we are working on further improving it and will update the repo regularly with improvements. 

> The final question is what does the data in Figure 10 illustrate compared to the data in Figure 9? I sincerely hope to get your reply and answer. Thank you very much！

Figures 9 and 10 are two different attitude strategies. Figure 9 shows a flight with the _zero-tilt_ attitude strategy, while Figure 10 shows a flight with the _fixed-tilt_ attitude strategy.

Btw, it will be really helpful if a new issue is opened for separate questions. That way everyone can find the answers to their questions just by looking at the issue titles :)
