### ISSUE TITLE
Consult the ROS code and related MATLAB code

### ISSUE THREAD

**Issue by daydayupcg137** [castacks/PX4-fully-actuated#10]
Hello, may I ask when will you release your ROS code and related MATLAB code?I want to learn more about it.

Thank you very much.

**Comment by keipour** [comment]
Hello! Thanks for your interest in our work. We are planning to release the MATLAB sim and a ROS interface in April. Although, please note that the ROS code to interface our PX4 code is similar to any other ROS code interfacing PX4 through MAVROS. You can learn how to connect to PX4 in ROS from here:

[https://docs.px4.io/master/en/ros/](https://docs.px4.io/master/en/ros/)

**Comment by daydayupcg137** [comment]
fine, thank you very much. Looking forward to your simulation code

**Comment by daydayupcg137** [comment]
Hello, may I ask you when you will release the Ros code and related MATLAB code in April ?
         Thank you very much for your reply and help。
         













At 2021-03-13 23:38:29, "Azarakhsh Keipour" ***@***.***> wrote:

Hello! Thanks for your interest in our work. We are planning to release the MATLAB sim and a ROS interface in April. Although, please note that the ROS code to interface our PX4 code is similar to any other ROS code interfacing PX4 through MAVROS. You can learn how to connect to PX4 in ROS from here:

https://docs.px4.io/master/en/ros/
