### ISSUE TITLE
How to establish the relationship between the tilt Angle alpha and Beta of the UAV in FX, FY, FZ？

### ISSUE THREAD

**Issue by daydayupcg137** [castacks/PX4-fully-actuated#12]
Excuse me, I have a question I hope you can help me.

As we all know, fully-actuated Hexarotor can generate forces along X,Y, and Z, and as the tilt Angle increases, Fx and Fy will get bigger and Fz will get smaller..
     
 So, how to establish the function relationship between Fx,Fy, Fz and the tilt Angle alpha and Beta,   This problem has been troubling me, Could you help me?

**Comment by daydayupcg137** [comment]
![image](https://user-images.githubusercontent.com/66363845/112252033-46c1fa00-8c97-11eb-918e-8623ade3591d.png)

In the above case, what is the relation of Fmax(fxmax/fymax/fzmax) with respect to the tilt Angle alpha and Beta?

I would be very grateful if you could help meThank you very much!

**Comment by keipour** [comment]
The relationship between the Fx, Fy, and Fz is very nonlinear and heavily depends on the geometry of your UAV. It is totally possible that for some geometry they are even totally independent. Generally, you can find the analysis on this relationship in the papers introducing a specific geometry and controller (it is often called dynamic manipulability or thrust set). We are planning to publish a paper around it soon.

**Comment by daydayupcg137** [comment]
Can we  figure out the force(FX, FY, FZ)  only by the distribution matrix M and some constant like wheelbase, mass.










At 2021-04-08 10:44:01, "Azarakhsh Keipour" ***@***.***> wrote:

The relationship between the Fx, Fy, and Fz is very nonlinear and heavily depends on the geometry of your UAV. It is totally possible that for some geometry they are even totally independent. Generally, you can find the analysis on this relationship in the papers introducing a specific geometry and controller (it is often called dynamic manipulability or thrust set). We are planning to publish a paper around it soon.

**Comment by keipour** [comment]
I am not sure what you mean by wheelbase, but yes, you can calculate the relationship just from your specific geometry. You can study [mixer_multirotor.py](https://github.com/castacks/PX4-fully-actuated/blob/v1.10-master/src/lib/mixer/MultirotorMixer/mixer_multirotor.py) in PX4 which autogenerates the matrix from the given geometry of the multirotor. Btw, mass does not affect the generated forces and moments, it only affects the generated accelerations from those forces and moments.

**Comment by daydayupcg137** [comment]
Thank you for your reply and help.Because when I was reading some articles, it directly figured out the relationship between the force(FX, FY, FZ) and the tilt Angle(alpha,Beta) based on the distribution matrix like the one shown below,















在 2021-04-08 11:17:33，"Azarakhsh Keipour" ***@***.***> 写道：

I am not sure what you mean by wheelbase, but yes, you can calculate the relationship just from your specific geometry. You can study mixer_multirotor.py in PX4 which autogenerates the matrix from the given geometry of the multirotor. Btw, mass does not affect the generated forces and moments, it only affects the generated accelerations from those forces and moments.

**Comment by daydayupcg137** [comment]
Sorry, I sent it by mistake just now.


 when I was reading some articles, it directly figured out the relationship between the force(FX, FY, FZ) and the tilt Angle(alpha,Beta) based on the distribution matrix like the one shown below,Therefore, I would like to consult how to deduce the relationship between output force and tilt Angle according to this matrix. I have read the relevant papers you just mentioned, but I have no ideas.I'm not sure if you can derive this relationship, can you explain the derivation process in detail?


    















在 2021-04-08 11:17:33，"Azarakhsh Keipour" ***@***.***> 写道：

I am not sure what you mean by wheelbase, but yes, you can calculate the relationship just from your specific geometry. You can study mixer_multirotor.py in PX4 which autogenerates the matrix from the given geometry of the multirotor. Btw, mass does not affect the generated forces and moments, it only affects the generated accelerations from those forces and moments.

**Comment by LizhichengDlut** [comment]
> Sorry, I sent it by mistake just now. when I was reading some articles, it directly figured out the relationship between the force(FX, FY, FZ) and the tilt Angle(alpha,Beta) based on the distribution matrix like the one shown below,Therefore, I would like to consult how to deduce the relationship between output force and tilt Angle according to this matrix. I have read the relevant papers you just mentioned, but I have no ideas.I'm not sure if you can derive this relationship, can you explain the derivation process in detail? 在 2021-04-08 11:17:33，"Azarakhsh Keipour" ***@***.***> 写道： I am not sure what you mean by wheelbase, but yes, you can calculate the relationship just from your specific geometry. You can study mixer_multirotor.py in PX4 which autogenerates the matrix from the given geometry of the multirotor. Btw, mass does not affect the generated forces and moments, it only affects the generated accelerations from those forces and moments. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我认为你可以通过无人机的几何构型推导出力和倾角的关系，我们可以讨论一下
