### ISSUE TITLE
Consult the latest article retrieval

### ISSUE THREAD

**Issue by daydayupcg137** [castacks/PX4-fully-actuated#14]
Hello, excuse me, May I ask when your latest articles can be retrieved online?

**Comment by keipour** [comment]
Sorry for the late reply. For future reference, here are the publications on this work excluding the related and follow-up works (all of the already-published ones are available on ArXiv as well):

**Thesis:** Azarakhsh Keipour. “Physical Interaction and Manipulation of the Environment using Aerial Robots”. PhD thesis. Pittsburgh, PA, USA: Carnegie Mellon University, May 2022. url: https://arxiv.org/abs/2207.02856.

**Paper on simulator:** Azarakhsh Keipour, Mohammadreza Mousaei, Dongwei Bai, Junyi Geng, and Sebastian Scherer. “UAS Simulator for Modeling, Analysis and Control in Free Flight and Physical Interaction”. In: AIAA SciTech 2023 Forum. National Harbor, MD, USA: American Institute of Aeronautics and Astronautics, Jan. 2023, pp. 1–7. doi: 10.2514/6.2023-1279. url: https://arc.aiaa.org/doi/abs/10.2514/6.2023-1279.

**Paper on setpoint strategies**: Azarakhsh Keipour, Mohammadreza Mousaei, Andrew T Ashley, and Sebastian Scherer. “Integration of Fully-Actuated Multirotors into Real-World Applications”. In: arXiv:2011.06666 (2020), pp. 1–5. doi: 10.48550/arxiv.2011.06666. url: https://arxiv.org/abs/2011.06666.

**Paper on wrench space analysis**: Azarakhsh Keipour, Mohammadreza Mousaei, Junyi Geng, and Sebastian Scherer. “Real-Time Wrench-Set Analysis and Applications for Aerial Robots”. in press.
