### ISSUE TITLE
Consult  the  Matlab Simulation Code

### ISSUE THREAD

**Issue by daydayup132** [castacks/PX4-fully-actuated#15]
Hello, may I ask if the Matlab simulation code on your official website will be open source?

![image](https://user-images.githubusercontent.com/52619617/117573074-93a74600-b108-11eb-8024-6f52d6a3a112.png)

**Comment by keipour** [comment]
Sorry for the very late reply. Adding the response for future reference:
Here is the code: https://github.com/keipour/aircraft-simulator-matlab
Here is the paper for the simulator: 
https://arc.aiaa.org/doi/abs/10.2514/6.2023-1279
https://arxiv.org/abs/2212.02973
