### ISSUE TITLE
About Firmware

### ISSUE THREAD

**Issue by LizhichengDlut** [castacks/PX4-fully-actuated#18]
after I upload the .px4 file in my Pixhawk, I select tilt hexarotor airframe, I found that props can't spin,when I change common hexarotor airframe, props can spin normally.How can I solve it? Thank you

**Comment by daydayup132** [comment]
hello,I have the same problem。We can have a talk.

**Comment by Jawad-RoboLearn** [comment]
Have you solved it?

**Comment by LizhichengDlut** [comment]
Yes, you should use Pixhawk mini, not Pixhawk.
Good luck to you!

**Comment by lygoon** [comment]
> Yes, you should use Pixhawk mini, not Pixhawk. Good luck to you!

I have a question.Can I use this firmware directly by using Pixhawk mini? Is there any other problem?Thank you.

**Comment by keipour** [comment]
> > Yes, you should use Pixhawk mini, not Pixhawk. Good luck to you!
> 
> I have a question.Can I use this firmware directly by using Pixhawk mini? Is there any other problem?Thank you.

We developed it on pixracer, but @LizhichengDlut reported (see above) that it also worked on pixhawk mini.

**Comment by LizhichengDlut** [comment]
> hello,I have the same problem。We can have a talk.

Sure, You can add my QQ or sent mail to: 3418023089@qq.com
