### ISSUE TITLE
the visual simulation code of MATLAB in the paper

### ISSUE THREAD

**Issue by daydayupcg137** [castacks/PX4-fully-actuated#2]
Hello, may I ask if you plan to share the visual simulation code of MATLAB?

**Comment by keipour** [comment]
Hi, yes, probably by the end of this month. Also, the guide to the SITL simulation for the fully-actuated PX4 will be added in the first week of December.

**Comment by daydayupcg137** [comment]
OK, look forward to your sharing, your work is very good

**Comment by keipour** [comment]
Hi, the instructions for the Gazebo SITL simulation are added to the README now. You can access the new files by pulling the latest changes.

**Comment by daydayupcg137** [comment]
Thank you very much. That's great
