### ISSUE TITLE
ninja: build stopped: subcommand failed. Makefile:200: recipe for target 'px4_sitl' failed

### ISSUE THREAD

**Issue by daydayupcg137** [castacks/PX4-fully-actuated#4]
Hi ,I have updated the latest program, But when I run "**make px4_sitl gazebo_hexa_x_tilt**" in the terminal,The application will get stuck in the interface below:
![image](https://user-images.githubusercontent.com/66363845/101456162-9a216e00-396e-11eb-9722-34eafd3e4f6a.png)
**After a few minutes:**
`cg@cg-virtual-machine:~/wort_src/newcode/PX4-fully-actuated$ make px4_sitl gazebo_hexa_x_tilt
[0/5] Performing build step for 'sitl_gazebo'
[5/52] Building CXX object CMakeFiles/...dir/src/gazebo_gst_camera_plugin.cpp.o
FAILED: CMakeFiles/gazebo_gst_camera_plugin.dir/src/gazebo_gst_camera_plugin.cpp.o 
/usr/bin/c++  -DLIBBULLET_VERSION=2.87 -DLIBBULLET_VERSION_GT_282 -Dgazebo_gst_camera_plugin_EXPORTS -isystem /usr/include/gazebo-9 -isystem /usr/include/bullet -isystem /usr/include/simbody -isystem /usr/include/sdformat-6.2 -isystem /usr/include/ignition/math4 -isystem /usr/include/OGRE -isystem /usr/include/OGRE/Terrain -isystem /usr/include/OGRE/Paging -isystem /usr/include/ignition/transport4 -isystem /usr/include/ignition/msgs1 -isystem /usr/include/ignition/common1 -isystem /usr/include/ignition/fuel_tools1 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/cg/wort_src/newcode/PX4-fully-actuated/Tools/sitl_gazebo/include -I. -I/usr/include/eigen3 -I/usr/include/eigen3/eigen3 -I/usr/include/gazebo-9/gazebo/msgs -I/home/cg/wort_src/newcode/PX4-fully-actuated/mavlink/include -isystem /usr/include/opencv -I/home/cg/wort_src/newcode/PX4-fully-actuated/Tools/sitl_gazebo/external/OpticalFlow/include -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/uuid -isystem /usr/include/x86_64-linux-gnu -Wno-deprecated-declarations -fPIC   -I/usr/include/uuid -I/usr/include/x86_64-linux-gnu -std=gnu++1z -MD -MT CMakeFiles/gazebo_gst_camera_plugin.dir/src/gazebo_gst_camera_plugin.cpp.o -MF CMakeFiles/gazebo_gst_camera_plugin.dir/src/gazebo_gst_camera_plugin.cpp.o.d -o CMakeFiles/gazebo_gst_camera_plugin.dir/src/gazebo_gst_camera_plugin.cpp.o -c /home/cg/wort_src/newcode/PX4-fully-actuated/Tools/sitl_gazebo/src/gazebo_gst_camera_plugin.cpp
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
[6/52] Building CXX object CMakeFiles/...dir/src/gazebo_mavlink_interface.cpp.o
ninja: build stopped: subcommand failed.
[1/5] Generating ../../logs
FAILED: external/Stamp/sitl_gazebo/sitl_gazebo-build 
cd /home/cg/wort_src/newcode/PX4-fully-actuated/build/px4_sitl_default/build_gazebo && /usr/bin/cmake --build .
ninja: build stopped: subcommand failed.
Makefile:200: recipe for target 'px4_sitl' failed
make: *** [px4_sitl] Error 1
`

It is not clear what caused the failure, my SWAP memory size increased to 1279M

**Comment by keipour** [comment]
There are some guidelines on how to fix different errors here:
https://dev.px4.io/master/en/simulation/gazebo.html

Please follow the instructions there to run iris simulation, then you can try hexa_x_tilt. 

Please let me know if you have issues with the instructions there.

> Hi ,I have updated the latest program, But when I run "**make px4_sitl gazebo_hexa_x_tilt**" in the terminal,The application will get stuck in the interface below:
> 
> ![image](https://user-images.githubusercontent.com/66363845/101456162-9a216e00-396e-11eb-9722-34eafd3e4f6a.png)
> 
> **After a few minutes:**
> 
> `cg@cg-virtual-machine:~/wort_src/newcode/PX4-fully-actuated$ make px4_sitl gazebo_hexa_x_tilt
> 
> [0/5] Performing build step for 'sitl_gazebo'
> 
> [5/52] Building CXX object CMakeFiles/...dir/src/gazebo_gst_camera_plugin.cpp.o
> 
> FAILED: CMakeFiles/gazebo_gst_camera_plugin.dir/src/gazebo_gst_camera_plugin.cpp.o 
> 
> /usr/bin/c++  -DLIBBULLET_VERSION=2.87 -DLIBBULLET_VERSION_GT_282 -Dgazebo_gst_camera_plugin_EXPORTS -isystem /usr/include/gazebo-9 -isystem /usr/include/bullet -isystem /usr/include/simbody -isystem /usr/include/sdformat-6.2 -isystem /usr/include/ignition/math4 -isystem /usr/include/OGRE -isystem /usr/include/OGRE/Terrain -isystem /usr/include/OGRE/Paging -isystem /usr/include/ignition/transport4 -isystem /usr/include/ignition/msgs1 -isystem /usr/include/ignition/common1 -isystem /usr/include/ignition/fuel_tools1 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/cg/wort_src/newcode/PX4-fully-actuated/Tools/sitl_gazebo/include -I. -I/usr/include/eigen3 -I/usr/include/eigen3/eigen3 -I/usr/include/gazebo-9/gazebo/msgs -I/home/cg/wort_src/newcode/PX4-fully-actuated/mavlink/include -isystem /usr/include/opencv -I/home/cg/wort_src/newcode/PX4-fully-actuated/Tools/sitl_gazebo/external/OpticalFlow/include -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/uuid -isystem /usr/include/x86_64-linux-gnu -Wno-deprecated-declarations -fPIC   -I/usr/include/uuid -I/usr/include/x86_64-linux-gnu -std=gnu++1z -MD -MT CMakeFiles/gazebo_gst_camera_plugin.dir/src/gazebo_gst_camera_plugin.cpp.o -MF CMakeFiles/gazebo_gst_camera_plugin.dir/src/gazebo_gst_camera_plugin.cpp.o.d -o CMakeFiles/gazebo_gst_camera_plugin.dir/src/gazebo_gst_camera_plugin.cpp.o -c /home/cg/wort_src/newcode/PX4-fully-actuated/Tools/sitl_gazebo/src/gazebo_gst_camera_plugin.cpp
> 
> c++: internal compiler error: 已杀死 (program cc1plus)
> 
> Please submit a full bug report,
> 
> with preprocessed source if appropriate.
> 
> See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
> 
> [6/52] Building CXX object CMakeFiles/...dir/src/gazebo_mavlink_interface.cpp.o
> 
> ninja: build stopped: subcommand failed.
> 
> [1/5] Generating ../../logs
> 
> FAILED: external/Stamp/sitl_gazebo/sitl_gazebo-build 
> 
> cd /home/cg/wort_src/newcode/PX4-fully-actuated/build/px4_sitl_default/build_gazebo && /usr/bin/cmake --build .
> 
> ninja: build stopped: subcommand failed.
> 
> Makefile:200: recipe for target 'px4_sitl' failed
> 
> make: *** [px4_sitl] Error 1
> 
> `
> 
> 
> 
> It is not clear what caused the failure, my SWAP memory size increased to 1279M
> 
> 
> 
>

**Comment by keipour** [comment]
I assume your issue is fixed. Closing the issue.
