### ISSUE TITLE
a question about the theory analysis of inclination Angle

### ISSUE THREAD

**Issue by daydayupcg137** [castacks/PX4-fully-actuated#5]
Excuse me, I have an idea through your project recently.Each arm of the UAV can actually tilt two degrees of freedom. I have seen some methods in some literature to do a multi-objective optimization algorithm from the perspective of energy efficiency and the maximum lateral contact force.I think this could be an improvement on your project because you have a fixed tilt of 30 degrees, but why?Now the question is, I don't know how to derive the relationship between the two objective functions of energy efficiency and the maximum lateral contact force with respect to the two angles?There is a literature called "Estimation and Optimization of Fully actuated Multirotor Platform with Nonparallel Actuation Mechanism". After reference, I still can't deduce the relation expression between them. Could you give me some help?
Looking forward to your reply. Thank you very much.

**Comment by keipour** [comment]
Sorry for the late reply. It was the holidays and I totally forgot to respond. 

Thanks for the suggestions. For each application and purpose, there is a different set of arm angles that is optimal and we were not trying to optimize for a specific purpose here and our tests were just to show that our proposed methods work on a general fully-actuated multirotor. As you mentioned, there are many papers that specifically look into optimizing the designs. 

Generally, the relations between these angles and their force/torque sets are not completely intuitive and there are no closed-form formulas. Many teams just run numerical methods to find the optimal angles for specific tasks or just do brute force. While it's rather easy to analyze and find optimal structure using our MATLAB simulator, it's not the focus of our work so I am probably not the best person to help you with those papers. You can possibly also contact the authors if you have specific questions or issues.

**Comment by daydayupcg137** [comment]
Thank you very much for your reply. I will continue to try to optimize the best Angle for the contact task.
      By the way, when will your source code  for a motion/force control task of drawing on the wall be released?I'm very interested in this demo.
















At 2021-01-05 07:28:50, "Azarakhsh Keipour" <notifications@github.com> wrote:

Sorry for the late reply. It was the holidays and I totally forgot to respond.

Thanks for the suggestions. For each application and purpose, there is a different set of arm angles that is optimal and we were not trying to optimize for a specific purpose here and our tests were just to show that our proposed methods work on a general fully-actuated multirotor. As you mentioned, there are many papers that specifically look into optimizing the designs.

Generally, the relations between these angles and their force/torque sets are not completely intuitive and there are no closed-form formulas. Many teams just run numerical methods to find the optimal angles for specific tasks or just do brute force. While it's rather easy to analyze and find optimal structure using our MATLAB simulator, it's not the focus of our work so I am probably not the best person to help you with those papers. You can possibly also contact the authors if you have specific questions or issues.

**Comment by keipour** [comment]
Thanks for your interest in the MATLAB simulation. It will be released soon. It needs some code cleaning and some refactoring to be more useful for others. Right now it is not ready and I'm a bit busy with something else, an will prepare it as soon as I get some time :)
