### ISSUE TITLE
What changes have you made to the PX4 source code?

### ISSUE THREAD

**Issue by daydayupcg137** [castacks/PX4-fully-actuated#6]
Hello,Thank you very much for your previous help.But I still have some questions.  I would like to ask how do you use the code of Pixhawk to control the Fully-actuated UAV?What changes have you made to the PX4 source code?Is it mainly about modifying the control allocation matrix?This control principle is not described in detail in your paper, so I hope to get your help.

**Comment by keipour** [comment]
> how do you use the code of Pixhawk to control the Fully-actuated UAV?

The control is very similar to the normal UAV using PX4, except that the attitude behavior is defined by the OMNI_ATT_MODE parameter. For example, in mode 2, the roll and pitch controllers will move the UAV on the horizontal plane very similar to the normal behavior except that there is no tilting anymore. I encourage you to try it out in the simulator to learn the behavior.

> What changes have you made to the PX4 source code? Is it mainly about modifying the control allocation matrix? This control principle is not described in detail in your paper, so I hope to get your help.

Control allocation needs to fit the structure of the drone and there are many papers describing different allocation methods. We modified PX4's control allocation to work with 3-D thrust and generate the allocation matrix for our drone, but it was not a novel contribution and thus was not the focus of the ICRA paper. You can use any method for control allocation. 

That said, the main changes to the source code related to the paper are in the position controller module. You can `git diff` our code with the last commit before my commits to see what changes we have made.

**Comment by daydayupcg137** [comment]
Thank you very much for your help. I will continue to learn your scheme.
