### ISSUE TITLE
How  to choose **Hexarotor x with tilted arms** airframe in the QGroundControl？

### ISSUE THREAD

**Issue by daydayupcg137** [castacks/PX4-fully-actuated#7]
![image](https://user-images.githubusercontent.com/66363845/104536440-10428000-5653-11eb-8fa9-f182d93d009f.png)

         Hello, after compiling the firmware and upload it on my hardware  through the QGroundControl. But I do not know how  to 

choose **Hexarotor x with tilted arms** airframe in the QGroundControl？

          By the way, what sensors are attached to your Pixracer? Like GPS, optical flow sensors?

**Comment by daydayupcg137** [comment]
![Uploading image.png…]()

After I updated a new QGroundControl,I find it.

**Comment by keipour** [comment]
>  Hello, after compiling the firmware and upload it on my hardware through the QGroundControl. But I do not know how to choose Hexarotor x with tilted arms airframe in the QGroundControl？

Great! One of my co-authors also reported that he couldn't see the `Hexarotor x with tilted arms` in the airframes. After flashing and reflashing a few times it just showed up. I personally never had an issue and it shows up on my QGroundControl every time. I assume it's a QGroundControl issue.
