### ISSUE TITLE
The actual flight condition of your fully-actuated UAV

### ISSUE THREAD

**Issue by daydayupcg137** [castacks/PX4-fully-actuated#9]
Hello, could you please tell me what effect your fully-actuated UAV can achieve in actual flight?Like:
      1.Hover horizontally in the air
      2.Hover in the air with the uav body tilted
      3......
      4.....
    
     How to achieve the website video contact with the wall environment job?Do you need a depth camera?

     Thank you very much for your help!

**Comment by keipour** [comment]
>   Hello, could you please tell me what effect your fully-actuated UAV can achieve in actual flight?Like:
>   1.Hover horizontally in the air
>   2.Hover in the air with the uav body tilted
>   3......
>   4.....

Hi, you can achieve all five attitude modes mentioned in the paper by changing the parameter OMNI_ATT_MODE to these:

0: Full-tilt attitude: Similar to underactuated UAVs, it always tilts in the direction of acceleration. Tilts towards the wind when hovering.

2: Zero-Tilt attitude: Tries to keep its attitude at zero in all conditions when flying and hovering.

1: Min-tilt attitude: Behaves like a fusion of 0 and 2, keeping it at zero, unless if it has to tilt, then it tilts in the same direction as mode 0 would tilt but with much less tilt.

3: Fixed-tilt attitude: Keeps the fixed tilt angle (to the value set in `OMNI_ATT_TLT_ANG`) and direction (to the value set in `OMNI_ATT_TLT_DIR`).

4: Fixed attitude: Keeps the fixed roll and pitch to the values set in `OMNI_ATT_ROLL` and `OMNI_ATT_PITCH`.

>  How to achieve the website video contact with the wall environment job?Do you need a depth camera?

If you want to do it fully autonomously you would probably need some way of measuring how far you are from the wall or if you have hit the wall already. Depending on your application and the level of required autonomy, you may use a depth camera, or an RTK, or a force sensor or simply command it to go forward until bumping into something or some other state estimation method. 

We do have a tracking camera which we use to help state estimation. But the point of putting the wall contact in the video is to show the robustness of the controller and the wall contact itself is irrelevant to this specific paper.
